apiVersion: v1
kind: Service
metadata:
  name: ms-auth-service
spec:
  type: NodePort
  selector:
    app: ms-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9096
      nodePort: 30036