version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: pass
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # datalari davamli saxlamaq ucun
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
