version: '3.8'

services:
  db:
    image: postgres
    container_name: authdb
    environment:
      POSTGRES_USERNAME: pass
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: authdb
    ports:
      - '5432-5432'